GET https://changelogs.md/api HTTP/1.1

## changelog from specific project
GET https://changelogs.md/api/github/facebook/react/ HTTP/1.1

## github releases
GET https://api.github.com/repos/kentcdodds/react-testing-library/releases HTTP/1.1
